# Generated by Django 3.1.2 on 2020-12-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythons_app', '0003_python_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='python',
            name='created_by',
        ),
    ]
